# Generated by Django 5.0.1 on 2024-02-01 11:23

import webhook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.CharField(default=webhook.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('company_id', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('headers', models.JSONField(blank=True, null=True)),
                ('events', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
